name: ripple_effect
description: An easy way to start a ripple effect from any widget to the entire screen on your flutter app.
version: 0.1.1
homepage: https://github.com/ericdallo/ripple_effect

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">= 1.12.1"

dependencies:
  flutter:
    sdk: flutter
  rect_getter: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
